/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  gallerySidebar: [{type: 'autogenerated', dirName: 'gallery'}],

  hackerSidebar: [
    'digitalsovereignty/newsletter/index',
    {
      type: 'category',
      label: 'Data Handling',
      items: [
        'digitalsovereignty/data/combine-images-into-pdf/index',
        'digitalsovereignty/data/convert-audio-m4a-into-video-mp4/index',
        'digitalsovereignty/data/tips-of-ffmpeg/index',
        'digitalsovereignty/data/merge-gps-activities/index',
        'digitalsovereignty/data/resize-multiple-images/index',
        'digitalsovereignty/data/transcribe-speech-into-text/index',
        'digitalsovereignty/data/add-subtitle-to-video/index',
        'digitalsovereignty/data/scrape-karaoke-mp3/index',
      ],
    },
    {
      type: 'category',
      label: 'Web3 & Blockchain',
      items: [
        'digitalsovereignty/web3/top-up-cycles-for-ic-canister/index',
        'digitalsovereignty/web3/nns-voting/index',
      ],
    },
    {
      type: 'category',
      label: 'Network & Infrastructure',
      items: [
        'digitalsovereignty/network/initialize-new-server-instance/index',
        'digitalsovereignty/network/fix-github-error-message/index',
        'digitalsovereignty/network/download-twitter-spaces-audio/index',
      ],
    },
    {
      type: 'category',
      label: 'macOS & Development',
      items: [
        'digitalsovereignty/mac/use-brew-on-m1-mac/index',
      ],
    },
  ],

  recordingSidebar: [{type: 'autogenerated', dirName: 'recording'}],

  cookbookSidebar: [
    'cookbook/index',
    {
      type: 'category',
      label: 'Recipes',
      items: [
        'cookbook/yang-fried-egg-rice/index',
        'cookbook/fried-veggie/index',
        'cookbook/rou-pian-chao-xi-hu-lu/index',
        'cookbook/tomato-stewed-beef/index',
        'cookbook/wuji-shan-yao-soup/index',
        'cookbook/qing-cai-dan-hua-soup/index',
        'cookbook/dan-cai-dong-gua-gou-ji-soup/index',
        'cookbook/gao-sheng-ribs/index',
        'cookbook/pork-fried-brocoli/index',
        'cookbook/tomato-za-cai-soup/index',
        'cookbook/rou-jia-mo/index',
        'cookbook/xia-chao-wan-dou/index',
        'cookbook/liang-ban-hua-cai/index',
        'cookbook/liang-ban-xi-qin/index',
        'cookbook/yu-xiang-rou-si/index',
        'cookbook/chicken-soup-bai-cai-qiao-mai-mian/index',
        'cookbook/tomato-fried-egg/index',
        'cookbook/kejia-xiao-chao/index',
        'cookbook/chicken-soup/index',
        'cookbook/ziran-lamb/index',
        'cookbook/korea-beef/index',
        'cookbook/gan-bian-si-ji-dou/index',
        'cookbook/huang-gua-rou-pian-chao-xiang-gan/index',
        'cookbook/jiang-bao-rou-ding/index',
        'cookbook/chicken-friend-mashroom/index',
        'cookbook/donggua-cha-ji-ding/index',
        'cookbook/dou-hua-yu-pian/index',
        'cookbook/liu-fei-chang/index',
        'cookbook/lotus-root-soup/index',
        'cookbook/lu-niu-rou/index',
        'cookbook/ribs-parrot-soup/index',
        'cookbook/shan-yao-chao-rou-pian/index',
        'cookbook/shanghai-qing/index',
        'cookbook/shao-zi-noodle/index',
        'cookbook/shredded-potato/index',
        'cookbook/teriyaki-chicken/index',
        'cookbook/tomato-egg-soup/index',
        'cookbook/shanghai-wonton-soup/index',
        'cookbook/steamed-minced-pork/index',
        'cookbook/pork-ribs-soup/index',
      ],
    },
  ],

  publicSidebar: [{type: 'autogenerated', dirName: 'public'}],

  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
