/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  gallerySidebar: [{type: 'autogenerated', dirName: 'gallery'}],

  hackerSidebar: [
    'digitalsovereignty/newsletter/index',
    {
      type: 'category',
      label: 'Data Handling',
      items: [
        'digitalsovereignty/data/combine-images-into-pdf/index',
        'digitalsovereignty/data/convert-audio-m4a-into-video-mp4/index',
        'digitalsovereignty/data/tips-of-ffmpeg/index',
        'digitalsovereignty/data/merge-gps-activities/index',
        'digitalsovereignty/data/resize-multiple-images/index',
        'digitalsovereignty/data/transcribe-speech-into-text/index',
        'digitalsovereignty/data/add-subtitle-to-video/index',
        'digitalsovereignty/data/scrape-karaoke-mp3/index',
      ],
    },
    {
      type: 'category',
      label: 'Web3 & Blockchain',
      items: [
        'digitalsovereignty/web3/top-up-cycles-for-ic-canister/index',
        'digitalsovereignty/web3/nns-voting/index',
      ],
    },
    {
      type: 'category',
      label: 'Network & Infrastructure',
      items: [
        'digitalsovereignty/network/initialize-new-server-instance/index',
        'digitalsovereignty/network/fix-github-error-message/index',
        'digitalsovereignty/network/download-twitter-spaces-audio/index',
      ],
    },
    {
      type: 'category',
      label: 'macOS & Development',
      items: [
        'digitalsovereignty/mac/use-brew-on-m1-mac/index',
      ],
    },
  ],

  recordingSidebar: [{type: 'autogenerated', dirName: 'recording'}],

  cookbookSidebar: [{type: 'autogenerated', dirName: 'cookbook'}],

  publicSidebar: [{type: 'autogenerated', dirName: 'public'}],

  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
