export const climb_peak_hong_kongPhotos = [
  {
    src: require('./img/watermarked_2-climb-peak-hong-kong-thepeak-01.jpg').default,
    width: 900,
    height: 1200,
    alt: 'Hong Kong Peak 1',
    caption: "夜行香港太平山顶 1",
    thumb: require('./img/thumbs/thumb-2-climb-peak-hong-kong-thepeak-01.jpg').default,
  },
  {
    src: require('./img/watermarked_2-climb-peak-hong-kong-thepeak-02.jpg').default,
    width: 900,
    height: 1200,
    alt: 'Hong Kong Peak 2',
    caption: "夜行香港太平山顶 2",
    thumb: require('./img/thumbs/thumb-2-climb-peak-hong-kong-thepeak-02.jpg').default,
  },
  {
    src: require('./img/watermarked_2-climb-peak-hong-kong-thepeak-03.jpg').default,
    width: 900,
    height: 1200,
    alt: 'Hong Kong Peak 3',
    caption: "夜行香港太平山顶 3",
    thumb: require('./img/thumbs/thumb-2-climb-peak-hong-kong-thepeak-03.jpg').default,
  },
  {
    src: require('./img/watermarked_2-climb-peak-hong-kong-thepeak-04.jpg').default,
    width: 900,
    height: 1200,
    alt: 'Hong Kong Peak 4',
    caption: "夜行香港太平山顶 4",
    thumb: require('./img/thumbs/thumb-2-climb-peak-hong-kong-thepeak-04.jpg').default,
  },
  {
    src: require('./img/watermarked_2-climb-peak-hong-kong-thepeak-05.jpg').default,
    width: 900,
    height: 1200,
    alt: 'Hong Kong Peak 5',
    caption: "夜行香港太平山顶 5",
    thumb: require('./img/thumbs/thumb-2-climb-peak-hong-kong-thepeak-05.jpg').default,
  },
  {
    src: require('./img/watermarked_2-climb-peak-hong-kong-thepeak-06.jpg').default,
    width: 900,
    height: 1200,
    alt: 'Hong Kong Peak 6',
    caption: "夜行香港太平山顶 6",
    thumb: require('./img/thumbs/thumb-2-climb-peak-hong-kong-thepeak-06.jpg').default,
  },
  {
    src: require('./img/watermarked_2-climb-peak-hong-kong-thepeak-07.jpg').default,
    width: 900,
    height: 1200,
    alt: 'Hong Kong Peak 7',
    caption: "夜行香港太平山顶 7",
    thumb: require('./img/thumbs/thumb-2-climb-peak-hong-kong-thepeak-07.jpg').default,
  },
  {
    src: require('./img/watermarked_2-climb-peak-hong-kong-thepeak-08.jpg').default,
    width: 900,
    height: 1200,
    alt: 'Hong Kong Peak 8',
    caption: "夜行香港太平山顶 8",
    thumb: require('./img/thumbs/thumb-2-climb-peak-hong-kong-thepeak-08.jpg').default,
  },
  {
    src: require('./img/watermarked_2-climb-peak-hong-kong-thepeak-09.jpg').default,
    width: 900,
    height: 1200,
    alt: 'Hong Kong Peak 9',
    caption: "夜行香港太平山顶 9",
    thumb: require('./img/thumbs/thumb-2-climb-peak-hong-kong-thepeak-09.jpg').default,
  },
];