export const san_franciscoPhotos = [
    {
      src: require('./img/5-san-francisco-SF_Chinatown_1_1024x1024.jpg').default,
      width: 900,
      height: 1200,
      alt: '5-san-francisco',
      caption: "SF Chinatown 1",
      thumb: require('./img/thumbs/thumb-5-san-francisco-SF_Chinatown_1_1024x1024.jpg').default,
    },
    {
      src: require('./img/5-san-francisco-SF_Chinatown_2_1024x1024.jpg').default,
      width: 900,
      height: 1200,
      alt: '5-san-francisco',
      caption: "SF Chinatown 2",
      thumb: require('./img/thumbs/thumb-5-san-francisco-SF_Chinatown_2_1024x1024.jpg').default,
    },
    {
      src: require('./img/5-san-francisco-SF_Chinatown_3_1024x1024.jpg').default,
      width: 900,
      height: 1200,
      alt: '5-san-francisco',
      caption: "SF Chinatown 3",
      thumb: require('./img/thumbs/thumb-5-san-francisco-SF_Chinatown_3_1024x1024.jpg').default,
    },
    {
      src: require('./img/5-san-francisco-SF_Chinatown_4_1024x1024.jpg').default,
      width: 900,
      height: 1200,
      alt: '5-san-francisco',
      caption: "SF Chinatown 4",
      thumb: require('./img/thumbs/thumb-5-san-francisco-SF_Chinatown_4_1024x1024.jpg').default,
    },
    {
      src: require('./img/5-san-francisco-SF_Chinatown_5_1024x1024.jpg').default,
      width: 900,
      height: 1200,
      alt: '5-san-francisco',
      caption: "SF Chinatown 5",
      thumb: require('./img/thumbs/thumb-5-san-francisco-SF_Chinatown_5_1024x1024.jpg').default,
    },
    {
      src: require('./img/5-san-francisco-SF_Cow_Hollow_1_1024x1024.jpg').default,
      width: 900,
      height: 1200,
      alt: '5-san-francisco',
      caption: "SF Cow Hollow 1",
      thumb: require('./img/thumbs/thumb-5-san-francisco-SF_Cow_Hollow_1_1024x1024.jpg').default,
    },
    {
      src: require('./img/5-san-francisco-SF_Cow_Hollow_2_1024x1024.jpg').default,
      width: 900,
      height: 1200,
      alt: '5-san-francisco',
      caption: "SF Cow Hollow 2",
      thumb: require('./img/thumbs/thumb-5-san-francisco-SF_Cow_Hollow_2_1024x1024.jpg').default,
    },
    {
      src: require('./img/5-san-francisco-SF_Cow_Hollow_3_1024x1024.jpg').default,
      width: 900,
      height: 1200,
      alt: '5-san-francisco',
      caption: "SF Cow Hollow 3",
      thumb: require('./img/thumbs/thumb-5-san-francisco-SF_Cow_Hollow_3_1024x1024.jpg').default,
    },
    {
      src: require('./img/5-san-francisco-SF_Cow_Hollow_4_1024x1024.jpg').default,
      width: 900,
      height: 1200,
      alt: '5-san-francisco',
      caption: "SF Cow Hollow 4",
      thumb: require('./img/thumbs/thumb-5-san-francisco-SF_Cow_Hollow_4_1024x1024.jpg').default,
    },
    {
      src: require('./img/5-san-francisco-SF_Cow_Hollow_5_1024x1024.jpg').default,
      width: 900,
      height: 1200,
      alt: '5-san-francisco',
      caption: "SF Cow Hollow 5",
      thumb: require('./img/thumbs/thumb-5-san-francisco-SF_Cow_Hollow_5_1024x1024.jpg').default,
    }

];
