export const vintageCarShowPhotos = [
  {
    src: require('./img/web/vintage-car-1.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-1",
    thumb: require('./img/thumbs/thumb_vintage-car-1.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-10.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-10",
    thumb: require('./img/thumbs/thumb_vintage-car-10.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-11.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-11",
    thumb: require('./img/thumbs/thumb_vintage-car-11.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-12.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-12",
    thumb: require('./img/thumbs/thumb_vintage-car-12.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-13.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-13",
    thumb: require('./img/thumbs/thumb_vintage-car-13.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-14.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-14",
    thumb: require('./img/thumbs/thumb_vintage-car-14.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-15.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-15",
    thumb: require('./img/thumbs/thumb_vintage-car-15.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-16.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-16",
    thumb: require('./img/thumbs/thumb_vintage-car-16.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-17.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-17",
    thumb: require('./img/thumbs/thumb_vintage-car-17.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-18.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-18",
    thumb: require('./img/thumbs/thumb_vintage-car-18.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-19.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-19",
    thumb: require('./img/thumbs/thumb_vintage-car-19.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-2.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-2",
    thumb: require('./img/thumbs/thumb_vintage-car-2.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-20.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-20",
    thumb: require('./img/thumbs/thumb_vintage-car-20.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-21.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-21",
    thumb: require('./img/thumbs/thumb_vintage-car-21.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-22.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-22",
    thumb: require('./img/thumbs/thumb_vintage-car-22.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-23.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-23",
    thumb: require('./img/thumbs/thumb_vintage-car-23.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-24.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-24",
    thumb: require('./img/thumbs/thumb_vintage-car-24.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-25.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-25",
    thumb: require('./img/thumbs/thumb_vintage-car-25.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-26.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-26",
    thumb: require('./img/thumbs/thumb_vintage-car-26.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-27.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-27",
    thumb: require('./img/thumbs/thumb_vintage-car-27.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-28.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-28",
    thumb: require('./img/thumbs/thumb_vintage-car-28.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-29.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-29",
    thumb: require('./img/thumbs/thumb_vintage-car-29.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-3.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-3",
    thumb: require('./img/thumbs/thumb_vintage-car-3.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-30.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-30",
    thumb: require('./img/thumbs/thumb_vintage-car-30.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-31.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-31",
    thumb: require('./img/thumbs/thumb_vintage-car-31.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-32.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-32",
    thumb: require('./img/thumbs/thumb_vintage-car-32.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-33.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-33",
    thumb: require('./img/thumbs/thumb_vintage-car-33.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-34.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-34",
    thumb: require('./img/thumbs/thumb_vintage-car-34.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-35.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-35",
    thumb: require('./img/thumbs/thumb_vintage-car-35.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-36.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-36",
    thumb: require('./img/thumbs/thumb_vintage-car-36.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-37.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-37",
    thumb: require('./img/thumbs/thumb_vintage-car-37.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-38.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-38",
    thumb: require('./img/thumbs/thumb_vintage-car-38.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-39.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-39",
    thumb: require('./img/thumbs/thumb_vintage-car-39.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-4.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-4",
    thumb: require('./img/thumbs/thumb_vintage-car-4.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-40.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-40",
    thumb: require('./img/thumbs/thumb_vintage-car-40.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-41.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-41",
    thumb: require('./img/thumbs/thumb_vintage-car-41.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-42.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-42",
    thumb: require('./img/thumbs/thumb_vintage-car-42.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-43.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-43",
    thumb: require('./img/thumbs/thumb_vintage-car-43.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-44.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-44",
    thumb: require('./img/thumbs/thumb_vintage-car-44.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-45.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-45",
    thumb: require('./img/thumbs/thumb_vintage-car-45.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-46.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-46",
    thumb: require('./img/thumbs/thumb_vintage-car-46.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-47.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-47",
    thumb: require('./img/thumbs/thumb_vintage-car-47.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-48.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-48",
    thumb: require('./img/thumbs/thumb_vintage-car-48.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-49.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-49",
    thumb: require('./img/thumbs/thumb_vintage-car-49.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-5.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-5",
    thumb: require('./img/thumbs/thumb_vintage-car-5.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-50.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-50",
    thumb: require('./img/thumbs/thumb_vintage-car-50.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-51.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-51",
    thumb: require('./img/thumbs/thumb_vintage-car-51.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-52.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-52",
    thumb: require('./img/thumbs/thumb_vintage-car-52.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-6.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-6",
    thumb: require('./img/thumbs/thumb_vintage-car-6.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-7.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-7",
    thumb: require('./img/thumbs/thumb_vintage-car-7.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-8.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-8",
    thumb: require('./img/thumbs/thumb_vintage-car-8.jpg').default,
  },
  {
    src: require('./img/web/vintage-car-9.jpg').default,
    width: 225,
    height: 300,
    alt: 'vintage-car-show',
    caption: "vintage-car-9",
    thumb: require('./img/thumbs/thumb_vintage-car-9.jpg').default,
  },
];
