export const xinjiangDay2Photos = [
  {
    src: require('./img/web/01_canyon_walk.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "峡谷里的西沙路很平坦",
    thumb: require('./img/thumbs/thumb_01_canyon_walk.jpg').default,
  },
  {
    src: require('./img/web/02_canyon_entrance.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "峡谷入口，碧空如洗，红岩似血",
    thumb: require('./img/thumbs/thumb_02_canyon_entrance.jpg').default,
  },
  {
    src: require('./img/web/03_canyon_path.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "峡谷常有落石",
    thumb: require('./img/thumbs/thumb_03_canyon_path.jpg').default,
  },
  {
    src: require('./img/web/04_canyon_cliff.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "这里的峭壁，攀岩有点难了，碎石太多",
    thumb: require('./img/thumbs/thumb_04_canyon_cliff.jpg').default,
  },
  {
    src: require('./img/web/05_canyon_turn.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "角落里有个少女泉",
    thumb: require('./img/thumbs/thumb_05_canyon_turn.jpg').default,
  },
  {
    src: require('./img/web/06_canyon_corner.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "难得人少",
    thumb: require('./img/thumbs/thumb_06_canyon_corner.jpg').default,
  },
  {
    src: require('./img/web/07_canyon_rocks.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "乱石穿空",
    thumb: require('./img/thumbs/thumb_07_canyon_rocks.jpg').default,
  },
  {
    src: require('./img/web/08_canyon_valley.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "谷底平坦，战乱时期应该是避难好处所",
    thumb: require('./img/thumbs/thumb_08_canyon_valley.jpg').default,
  },
  {
    src: require('./img/web/09_canyon_narrow_seam.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "一线天，考验 BMI 是否超标",
    thumb: require('./img/thumbs/thumb_09_canyon_narrow_seam.jpg').default,
  },
  {
    src: require('./img/web/10_canyon_boy.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "峡谷里的男孩",
    thumb: require('./img/thumbs/thumb_10_canyon_boy.jpg').default,
  },
  {
    src: require('./img/web/11_canyon_theatre.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "峡谷里的歌剧院",
    thumb: require('./img/thumbs/thumb_11_canyon_theatre.jpg').default,
  },
  {
    src: require('./img/web/12_canyon_exit.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "看到水了！印第安纳琼斯在哪里？",
    thumb: require('./img/thumbs/thumb_12_canyon_exit.jpg').default,
  },
  {
    src: require('./img/web/13_canyon_camels.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "还可以骑骆驼",
    thumb: require('./img/thumbs/thumb_13_canyon_camels.jpg').default,
  },
  {
    src: require('./img/web/14_canyon_gate.jpg').default,
    width: 300,
    height: 225,
    alt: 'xinjiang-day-2',
    caption: "远看是个小号的美国大峡谷",
    thumb: require('./img/thumbs/thumb_14_canyon_gate.jpg').default,
  },
  {
    src: require('./img/web/15_Kizil_cave_temple_river.jpg').default,
    width: 300,
    height: 225,
    alt: 'xinjiang-day-2',
    caption: "克弥尔石窟边竟然有条河",
    thumb: require('./img/thumbs/thumb_15_Kizil_cave_temple_river.jpg').default,
  },
  {
    src: require('./img/web/16__Kizil_cave_temple_buddha.jpg').default,
    width: 300,
    height: 225,
    alt: 'xinjiang-day-2',
    caption: "Kumarajiva 佛像",
    thumb: require('./img/thumbs/thumb_16__Kizil_cave_temple_buddha.jpg').default,
  },
  {
    src: require('./img/web/17__Kizil_cave_temple_caves.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "这里有300多个石窟",
    thumb: require('./img/thumbs/thumb_17__Kizil_cave_temple_caves.jpg').default,
  },
  {
    src: require('./img/web/18__Kizil_cave_temple_stairs.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-2',
    caption: "对大众开放的石窟有六个，特殊的石窟有两个",
    thumb: require('./img/thumbs/thumb_18__Kizil_cave_temple_stairs.jpg').default,
  },
];
