export const xinjiangDay1Photos = [
  {
    src: require('./img/web/01_street_pattern.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "库车大寺击鼓巷街景",
    thumb: require('./img/thumbs/thumb_01_street_pattern.jpg').default,
  },
  {
    src: require('./img/web/02_icecream.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "冰切糕的遐想",
    thumb: require('./img/thumbs/thumb_02_icecream.jpg').default,
  },
  {
    src: require('./img/web/03_kucha_coffee.jpg').default,
    width: 224,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "一阳古堡餐厅香味浓郁的库车老城咖啡",
    thumb: require('./img/thumbs/thumb_03_kucha_coffee.jpg').default,
  },
  {
    src: require('./img/web/04_street_pattern.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "午后阳光洒在库车大寺击鼓巷",
    thumb: require('./img/thumbs/thumb_04_street_pattern.jpg').default,
  },
  {
    src: require('./img/web/05_big_temple_tea_room.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "库车大寺的茶室",
    thumb: require('./img/thumbs/thumb_05_big_temple_tea_room.jpg').default,
  },
  {
    src: require('./img/web/06_big_temple_hall.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "库车大寺的大殿有点像摩尔人风格的阿尔罕伯拉宫",
    thumb: require('./img/thumbs/thumb_06_big_temple_hall.jpg').default,
  },
  {
    src: require('./img/web/07_big_temple_corridor.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "库车大寺大殿里的阳光",
    thumb: require('./img/thumbs/thumb_07_big_temple_corridor.jpg').default,
  },
  {
    src: require('./img/web/08_big_temple_light.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "阳光穿过库车大寺大殿的窗户趴在地毯上",
    thumb: require('./img/thumbs/thumb_08_big_temple_light.jpg').default,
  },
  {
    src: require('./img/web/09_big_temple_pie.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "古城区主街道热斯坦路的新疆烤馕",
    thumb: require('./img/thumbs/thumb_09_big_temple_pie.jpg').default,
  },
  {
    src: require('./img/web/10_parrots.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "两只鹦鹉在库车老城的小店里",
    thumb: require('./img/thumbs/thumb_10_parrots.jpg').default,
  },
  {
    src: require('./img/web/11_boy_with_pie.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "深谙新疆烤馕之道的男孩",
    thumb: require('./img/thumbs/thumb_11_boy_with_pie.jpg').default,
  },
  {
    src: require('./img/web/12_bbq_man.jpg').default,
    width: 300,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "忙碌的烤肉大叔",
    thumb: require('./img/thumbs/thumb_12_bbq_man.jpg').default,
  },
  {
    src: require('./img/web/13_pie_coffee.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-day-1',
    caption: "本地特色的馕咖啡，有点像 SeeSaw 咖啡的网红爆款煤球咖啡",
    thumb: require('./img/thumbs/thumb_13_pie_coffee.jpg').default,
  },
];
