export const deyoung_museumPhotos = [
    {
      src: require('./img/web/2-deyoung-museum-deYoung_stairway.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-deyoung-museum',
      caption: "San Francisco deYoung Museum",
      thumb: require('./img/thumbs/thumb-2-deyoung-museum-deYoung_stairway.jpg').default,
    },
    {
      src: require('./img/web/2-deyoung-museum-deYoung_waiting.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-deyoung-museum',
      caption: "San Francisco deYoung Museum",
      thumb: require('./img/thumbs/thumb-2-deyoung-museum-deYoung_waiting.jpg').default,
    },
    {
      src: require('./img/web/2-deyoung-museum-deYoung_whisper.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-deyoung-museum',
      caption: "San Francisco deYoung Museum",
      thumb: require('./img/thumbs/thumb-2-deyoung-museum-deYoung_whisper.jpg').default,
    },
    {
      src: require('./img/web/2-deyoung-museum-deYoung_perplexed.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-deyoung-museum',
      caption: "San Francisco deYoung Museum",
      thumb: require('./img/thumbs/thumb-2-deyoung-museum-deYoung_perplexed.jpg').default,
    },
    {
      src: require('./img/web/2-deyoung-museum-deYoung_chaos.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-deyoung-museum',
      caption: "San Francisco deYoung Museum",
      thumb: require('./img/thumbs/thumb-2-deyoung-museum-deYoung_chaos.jpg').default,
    },
    {
      src: require('./img/web/2-deyoung-museum-deYoung_climb.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-deyoung-museum',
      caption: "San Francisco deYoung Museum",
      thumb: require('./img/thumbs/thumb-2-deyoung-museum-deYoung_climb.jpg').default,
    },
    {
      src: require('./img/web/2-deyoung-museum-deYoung_division.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-deyoung-museum',
      caption: "San Francisco deYoung Museum",
      thumb: require('./img/thumbs/thumb-2-deyoung-museum-deYoung_division.jpg').default,
    },
    {
      src: require('./img/web/2-deyoung-museum-deYoung_fallen_angel.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-deyoung-museum',
      caption: "San Francisco deYoung Museum",
      thumb: require('./img/thumbs/thumb-2-deyoung-museum-deYoung_fallen_angel.jpg').default,
    },
    {
      src: require('./img/web/2-deyoung-museum-deYoung_fountain.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-deyoung-museum',
      caption: "San Francisco deYoung Museum",
      thumb: require('./img/thumbs/thumb-2-deyoung-museum-deYoung_fountain.jpg').default,
    }

];
