export const xinjiangCityPhotos = [
  {
    src: require('./img/web/01_guitarist.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "莎车老城区喀赞其街随处可见的传统艺人",
    thumb: require('./img/thumbs/thumb_01_guitarist.jpg').default,
  },
  {
    src: require('./img/web/02_cradle.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "丝路重镇莎车以代代相传的婴儿摇篮著名",
    thumb: require('./img/thumbs/thumb_02_cradle.jpg').default,
  },
  {
    src: require('./img/web/03_gourd.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "新疆的葫芦，可以用来装酒，据说口感清凉解暑",
    thumb: require('./img/thumbs/thumb_03_gourd.jpg').default,
  },
  {
    src: require('./img/web/04_water_bottles.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "色彩斑斓的水壶",
    thumb: require('./img/thumbs/thumb_04_water_bottles.jpg').default,
  },
  {
    src: require('./img/web/05_rugs.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "当地的羊毛地毯也可以相传好几代人",
    thumb: require('./img/thumbs/thumb_05_rugs.jpg').default,
  },
  {
    src: require('./img/web/10_butcher.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "在南疆的几天，每天吃各种羊肉",
    thumb: require('./img/thumbs/thumb_10_butcher.jpg').default,
  },
  {
    src: require('./img/web/11_weaver.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "编制挂毯的传统纺织机",
    thumb: require('./img/thumbs/thumb_11_weaver.jpg').default,
  },
  {
    src: require('./img/web/13_rug_brusher.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "地毯每年有一次需要用刷子刷干净",
    thumb: require('./img/thumbs/thumb_13_rug_brusher.jpg').default,
  },
  {
    src: require('./img/web/14_blacksmith.jpg').default,
    width: 224,
    height: 300,
    alt: 'xinjiang-city',
    caption: "西域中心喀什古城硕果仅存的铁匠铺",
    thumb: require('./img/thumbs/thumb_14_blacksmith.jpg').default,
  },
  {
    src: require('./img/web/15_dancer.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "踏吉美蓝美食宫的维吾尔族舞蹈表演",
    thumb: require('./img/thumbs/thumb_15_dancer.jpg').default,
  },
  {
    src: require('./img/web/21_spinning_top.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "让陀螺保持直立旋转的关键，是鞭击在中部",
    thumb: require('./img/thumbs/thumb_21_spinning_top.jpg').default,
  },
  {
    src: require('./img/web/22_spinning_top.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "围观的当地人里很多在跃跃欲试下场指导",
    thumb: require('./img/thumbs/thumb_22_spinning_top.jpg').default,
  },
  {
    src: require('./img/web/31_restaurant.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "金碧辉煌的踏吉美蓝美食宫",
    thumb: require('./img/thumbs/thumb_31_restaurant.jpg').default,
  },
  {
    src: require('./img/web/32_tamarisk_skewer.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "红柳木烤串，香滋滋的羊肉",
    thumb: require('./img/thumbs/thumb_32_tamarisk_skewer.jpg').default,
  },
  {
    src: require('./img/web/33_rack_meat.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "销魂的架子肉",
    thumb: require('./img/thumbs/thumb_33_rack_meat.jpg').default,
  },
  {
    src: require('./img/web/41_pigeon.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "这里的鸽子长得像孔雀",
    thumb: require('./img/thumbs/thumb_41_pigeon.jpg').default,
  },
  {
    src: require('./img/web/42_pigeons.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "最贵的一只鸽子上万元",
    thumb: require('./img/thumbs/thumb_42_pigeons.jpg').default,
  },
  {
    src: require('./img/web/51_gaotai_building.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "高台民居的下午",
    thumb: require('./img/thumbs/thumb_51_gaotai_building.jpg').default,
  },
  {
    src: require('./img/web/52_gaotai_overlook.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "当地原住民散去的十年后，高台民居变得像加沙地带",
    thumb: require('./img/thumbs/thumb_52_gaotai_overlook.jpg').default,
  },
  {
    src: require('./img/web/54_west_city_tower.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "喀什西古城的可以看到地标电视塔",
    thumb: require('./img/thumbs/thumb_54_west_city_tower.jpg').default,
  },
  {
    src: require('./img/web/55_west_city_corner.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "喀什西古城的角落，有点意大利五渔村的意思",
    thumb: require('./img/thumbs/thumb_55_west_city_corner.jpg').default,
  },
  {
    src: require('./img/web/56_west_city_coffee_house.jpg').default,
    width: 225,
    height: 300,
    alt: 'xinjiang-city',
    caption: "喀什西古城的入迷咖啡馆墙上的谜语",
    thumb: require('./img/thumbs/thumb_56_west_city_coffee_house.jpg').default,
  },
];
