export const simingshan_dragon_boatPhotos = [
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_01.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_01.JPG').default,
    },
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_02.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_02.JPG').default,
    },
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_03.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_03.JPG').default,
    },
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_04.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_04.JPG').default,
    },
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_05.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_05.JPG').default,
    },
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_06.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_06.JPG').default,
    },
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_07.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_07.JPG').default,
    },
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_08.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_08.JPG').default,
    },
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_09.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_09.JPG').default,
    },
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_10.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_10.JPG').default,
    },
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_11.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_11.JPG').default,
    },
    {
      src: require('./img/web/watermarked_1-simingshan-dragon-boat-img_202306_simingshan_12.JPG').default,
      width: 900,
      height: 1200,
      alt: '1-simingshan-dragon-boat',
      caption: "四明山",
      thumb: require('./img/thumbs/thumb-1-simingshan-dragon-boat-img_202306_simingshan_12.JPG').default,
    }

];
