export const park_dancersPhotos = [
    {
      src: require('./img/2-park-dancers-Park_Dancers_1.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-park-dancers',
      caption: "park dancers 1",
      thumb: require('./img/thumbs/thumb-2-park-dancers-Park_Dancers_1.jpg').default,
    },
    {
      src: require('./img/2-park-dancers-Park_Dancers_2.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-park-dancers',
      caption: "park dancers 2",
      thumb: require('./img/thumbs/thumb-2-park-dancers-Park_Dancers_2.jpg').default,
    },
    {
      src: require('./img/2-park-dancers-Park_Dancers_3.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-park-dancers',
      caption: "park dancers 3",
      thumb: require('./img/thumbs/thumb-2-park-dancers-Park_Dancers_3.jpg').default,
    },
    {
      src: require('./img/2-park-dancers-Park_Dancers_4.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-park-dancers',
      caption: "park dancers 4",
      thumb: require('./img/thumbs/thumb-2-park-dancers-Park_Dancers_4.jpg').default,
    },
    {
      src: require('./img/2-park-dancers-Park_Dancers_5.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-park-dancers',
      caption: "park dancers 5",
      thumb: require('./img/thumbs/thumb-2-park-dancers-Park_Dancers_5.jpg').default,
    },
    {
      src: require('./img/2-park-dancers-Park_Dancers_6.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-park-dancers',
      caption: "park dancers 6",
      thumb: require('./img/thumbs/thumb-2-park-dancers-Park_Dancers_6.jpg').default,
    },
    {
      src: require('./img/2-park-dancers-Park_Dancers_7.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-park-dancers',
      caption: "park dancers 7",
      thumb: require('./img/thumbs/thumb-2-park-dancers-Park_Dancers_7.jpg').default,
    },
    {
      src: require('./img/2-park-dancers-Park_Dancers_8.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-park-dancers',
      caption: "park dancers 8",
      thumb: require('./img/thumbs/thumb-2-park-dancers-Park_Dancers_8.jpg').default,
    },
    {
      src: require('./img/2-park-dancers-Park_Dancers_9.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-park-dancers',
      caption: "park dancers 9",
      thumb: require('./img/thumbs/thumb-2-park-dancers-Park_Dancers_9.jpg').default,
    },
    {
      src: require('./img/2-park-dancers-Park_Dancers_10.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-park-dancers',
      caption: "park dancers 10",
      thumb: require('./img/thumbs/thumb-2-park-dancers-Park_Dancers_10.jpg').default,
    },
    {
      src: require('./img/2-park-dancers-Park_Dancers_11.jpg').default,
      width: 900,
      height: 1200,
      alt: '2-park-dancers',
      caption: "park dancers 11",
      thumb: require('./img/thumbs/thumb-2-park-dancers-Park_Dancers_11.jpg').default,
    }

];
