export const kennedySpaceCenterPhotos = [
  {
    src: require('./img/web/01_rocket_garden.jpg').default,
    width: 300,
    height: 225,
    alt: 'kennedy-space-center',
    caption: "rocket garden",
    thumb: require('./img/thumbs/thumb_01_rocket_garden.jpg').default,
  },
  {
    src: require('./img/web/02_atlantis_front.jpg').default,
    width: 300,
    height: 225,
    alt: 'kennedy-space-center',
    caption: "atlantis front",
    thumb: require('./img/thumbs/thumb_02_atlantis_front.jpg').default,
  },
  {
    src: require('./img/web/03_atlantis_side.jpg').default,
    width: 300,
    height: 225,
    alt: 'kennedy-space-center',
    caption: "atlantis side",
    thumb: require('./img/thumbs/thumb_03_atlantis_side.jpg').default,
  },
  {
    src: require('./img/web/04_atlantis_engine.jpg').default,
    width: 300,
    height: 225,
    alt: 'kennedy-space-center',
    caption: "atlantis engine",
    thumb: require('./img/thumbs/thumb_04_atlantis_engine.jpg').default,
  },
  {
    src: require('./img/web/05_atlantis_back.jpg').default,
    width: 225,
    height: 300,
    alt: 'kennedy-space-center',
    caption: "atlantis back",
    thumb: require('./img/thumbs/thumb_05_atlantis_back.jpg').default,
  },
  {
    src: require('./img/web/06_control_room.jpg').default,
    width: 163,
    height: 300,
    alt: 'kennedy-space-center',
    caption: "control room",
    thumb: require('./img/thumbs/thumb_06_control_room.jpg').default,
  },
  {
    src: require('./img/web/07_wings.jpg').default,
    width: 225,
    height: 300,
    alt: 'kennedy-space-center',
    caption: "wings",
    thumb: require('./img/thumbs/thumb_07_wings.jpg').default,
  },
  {
    src: require('./img/web/08_atlantis_close.jpg').default,
    width: 225,
    height: 300,
    alt: 'kennedy-space-center',
    caption: "atlantis close",
    thumb: require('./img/thumbs/thumb_08_atlantis_close.jpg').default,
  },
  {
    src: require('./img/web/09_atlantis_inisde.jpg').default,
    width: 300,
    height: 225,
    alt: 'kennedy-space-center',
    caption: "atlantis inisde",
    thumb: require('./img/thumbs/thumb_09_atlantis_inisde.jpg').default,
  },
  {
    src: require('./img/web/10_space_shuttle.jpg').default,
    width: 225,
    height: 300,
    alt: 'kennedy-space-center',
    caption: "space shuttle",
    thumb: require('./img/thumbs/thumb_10_space_shuttle.jpg').default,
  },
  {
    src: require('./img/web/11_lawn.jpg').default,
    width: 300,
    height: 225,
    alt: 'kennedy-space-center',
    caption: "lawn",
    thumb: require('./img/thumbs/thumb_11_lawn.jpg').default,
  },
  {
    src: require('./img/web/12_mission_control.jpg').default,
    width: 300,
    height: 203,
    alt: 'kennedy-space-center',
    caption: "mission control",
    thumb: require('./img/thumbs/thumb_12_mission_control.jpg').default,
  },
  {
    src: require('./img/web/12_thrusters.jpg').default,
    width: 253,
    height: 300,
    alt: 'kennedy-space-center',
    caption: "thrusters",
    thumb: require('./img/thumbs/thumb_12_thrusters.jpg').default,
  },
  {
    src: require('./img/web/13_thrusters_below.jpg').default,
    width: 300,
    height: 225,
    alt: 'kennedy-space-center',
    caption: "thrusters below",
    thumb: require('./img/thumbs/thumb_13_thrusters_below.jpg').default,
  },
  {
    src: require('./img/web/14_cables.jpg').default,
    width: 300,
    height: 225,
    alt: 'kennedy-space-center',
    caption: "cables",
    thumb: require('./img/thumbs/thumb_14_cables.jpg').default,
  },
  {
    src: require('./img/web/15_booster.jpg').default,
    width: 225,
    height: 300,
    alt: 'kennedy-space-center',
    caption: "booster",
    thumb: require('./img/thumbs/thumb_15_booster.jpg').default,
  },
  {
    src: require('./img/web/16_capsule.jpg').default,
    width: 225,
    height: 300,
    alt: 'kennedy-space-center',
    caption: "capsule",
    thumb: require('./img/thumbs/thumb_16_capsule.jpg').default,
  },
  {
    src: require('./img/web/17_launchpad_39.jpg').default,
    width: 300,
    height: 225,
    alt: 'kennedy-space-center',
    caption: "launchpad 39",
    thumb: require('./img/thumbs/thumb_17_launchpad_39.jpg').default,
  },
  {
    src: require('./img/web/18_gantry.jpg').default,
    width: 232,
    height: 300,
    alt: 'kennedy-space-center',
    caption: "gantry",
    thumb: require('./img/thumbs/thumb_18_gantry.jpg').default,
  },
  {
    src: require('./img/web/19_dream_chaser.jpg').default,
    width: 225,
    height: 300,
    alt: 'kennedy-space-center',
    caption: "dream chaser",
    thumb: require('./img/thumbs/thumb_19_dream_chaser.jpg').default,
  },
  {
    src: require('./img/web/20_dream_chaser_back.jpg').default,
    width: 225,
    height: 300,
    alt: 'kennedy-space-center',
    caption: "dream chaser back",
    thumb: require('./img/thumbs/thumb_20_dream_chaser_back.jpg').default,
  },
  {
    src: require('./img/web/21_dream_chaser_wing.jpg').default,
    width: 300,
    height: 225,
    alt: 'kennedy-space-center',
    caption: "dream chaser wing",
    thumb: require('./img/thumbs/thumb_21_dream_chaser_wing.jpg').default,
  },
];
