export const lives_under_seaPhotos = [
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_1.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_1.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_2.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_2.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_3.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_3.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_4.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_4.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_5.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_5.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_6.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_6.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_7.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_7.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_8.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_8.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_9.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_9.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_10.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_10.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_11.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_11.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_12.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_12.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_13.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_13.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_jelly_1.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium Jelly Fish",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_jelly_1.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_jelly_2.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium Jelly Fish",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_jelly_2.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_jelly_3.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium Jelly Fish",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_jelly_3.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_jelly_4.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium Jelly Fish",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_jelly_4.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_jelly_5.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium Jelly Fish",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_jelly_5.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_jelly_6.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium Jelly Fish",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_jelly_6.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_jelly_7.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium Jelly Fish",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_jelly_7.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_jelly_8.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium Jelly Fish",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_jelly_8.jpg').default,
    },
    {
      src: require('./img/3-lives-under-sea-Monterey_Aquarium_jelly_9.jpg').default,
      width: 900,
      height: 1200,
      alt: '3-lives-under-sea',
      caption: "Monterey Bay Aquarium Jelly Fish",
      thumb: require('./img/thumbs/thumb-3-lives-under-sea-Monterey_Aquarium_jelly_9.jpg').default,
    }

];
